name: Dynamic README
on:
  schedule:
    - cron: "0 0 * * 2,5"
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - run: npm install

      - run: npm run start

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: 'README.md data/posts.json'
          commit_message: update readme by workflow
